# This is a basic workflow to help you get started with Actions

name: Release to github using @electron-delta/builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          architecture: 'x64'

      - name: npm install
        run: npm ci

      - name: change version
        run: node build_scripts/change-version.js

      - name: configure git
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "chnage version"
          npm version patch
          git commit -m "release skip ci" --amend

      - name: electron builder build and publish
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
